import Head from "next/head";
import Navbar from "@/component/Navbar";
import Hero from "@/component/Hero";
import Footer from "@/component/Footer";
import About from "@/component/About";
import { useRouter } from "next/router";
import { useAuthContext } from "@/context/AuthContext";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();
  const { user } = useAuthContext();
  useEffect(() => {
    if (user !== null) router.push("/admin");
  }, [user]);
  return (
    <>
      <Head>
        <title>Kasir Bengkel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero
        onSignInHandler={() => {
          router.push("/login");
        }}
      />
      <About />
      <Footer />
    </>
  );
}
