import SignupCard from "@/component/Signup";
import Head from "next/head";
import Navbar from "@/component/Navbar";
import Hero from "@/component/Hero";
import Footer from "@/component/Footer";
import About from "@/component/About";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kasir Bengkel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Footer />
    </>
  );
}
